### ISSUE TITLE
OneOps-Controller Failure

### ISSUE THREAD

**Issue by billheck** [oneops/oneops#369]
Hello,

I'm trying to get OneOps installed on CentOS 7 and I keep running into a roadblock with the OneOps-Controller section:  

FAILURE! - in TestSuite
(com.oneops.controller.workflow.DeployerTest)  Time elapsed: 0.286 sec  <<< FAILURE!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'getDataSource' defined in com.oneops.controller.workflow.DeployerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'getDataSource' threw exception; nested exception is com.google.common.base.VerifyException: Process [/tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin/initdb, -A, trust, -U, postgres, -D, /tmp/embedded-pg/8bec53b3-e507-4362-b5d8-f5c3773f19dd, -E, UTF-8] failed

Caused by: org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [javax.sql.DataSource]: Factory method 'getDataSource' threw exception; nested exception is com.google.common.base.VerifyException: Process [/tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin/initdb, -A, trust, -U, postgres, -D, /tmp/embedded-pg/8bec53b3-e507-4362-b5d8-f5c3773f19dd, -E, UTF-8] failed

Caused by: com.google.common.base.VerifyException: 
Process [/tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin/initdb, -A, trust, -U, postgres, -D, /tmp/embedded-pg/8bec53b3-e507-4362-b5d8-f5c3773f19dd, -E, UTF-8] failed

Any assistance is appreciated!

**Comment by manukgr** [comment]
@billheck I am also facing the same issue, Is this resolved at your end?

**Comment by ramanutd** [comment]
Hi,
I tried deploying OneOps on GCP Ubuntu 16.04 instance with 4 GB RAM. I am facing the same issue with oneops installation.
I also got the following error during mvn clean install. Please let me know how to resolve this issue.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project controller: There are test failures.                                                                                
[ERROR] 
[ERROR] Please refer to /opt/oneops/controller/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
```

If anyone else faced the same issue, please let me know how to resolve this issue.
Thanks.

**Comment by manukgr** [comment]
@rvirdiz problem was solved by initializing the gson object not by new Gson() but by below in WoProviderTest.java:
`//	private Gson gson = new Gson();  Comment this and add the next line`
`	private Gson gson= new GsonBuilder().setDateFormat("MMM w, Y k:m:s a").create();`

**Comment by ngupta7** [comment]
i did the change as recommended in the last comment ,still seeing the same errors:

Error creating bean with name 'getDataSource' defined in com.oneops.controller.workflow.DeployerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'getDataSource' threw exception; nested exception is com.google.common.base.VerifyException: Process [/tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin/initdb, -A, trust, -U, postgres, -D, /tmp/embedded-pg/12e7d8f2-ca01-445a-9da6-3bce40423b9a, -E, UTF-8] failed

Caused by: org.springframework.beans.BeanInstantiationException:
Failed to instantiate [javax.sql.DataSource]: Factory method 'getDataSource' threw exception; nested exception is com.google.common.base.VerifyException: Process [/tmp/embedded-pg/PG-785b618641f5eefce5b5079f2c9458dd/bin/initdb, -A, trust, -U, postgres, -D, /tmp/embedded-pg/12e7d8f2-ca01-445a-9da6-3bce40423b9a, -E, UTF-8] failed

**Comment by xevelzol** [comment]
this will skip unit test on this plugin:
$ vi pom.xml:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.19.1</version>
    <configuration>
        <testFailureIgnore>true</testFailureIgnore>
    </configuration>
</plugin>
```
make sure line `<testFailureIgnore>true</testFailureIgnore>` is inside configuration section

**Comment by ictinc** [comment]
I'm trying to install oneops on a ubuntu18.04 droplet. I've installed all the prerequisites as mentioned on oneops.com.
However when I run "mvn clean install" I'm being greeted with the errors mentioned in this thread:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project controller: There are test failures.                                                                                
[ERROR] 
[ERROR] Please refer to /opt/oneops/controller/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]

I've tried @rvirdiz solution and xevelzol which results in a different compilation error, symbol not found, referring to the line from @rvirdiz solution. When I remove that and only keep that of xevelzol it's going further only to provide me with an error on "Display".

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default) on project display: Command execution failed.: Process exited with an error: 7 (Exit value: 7) -> [Help 1]

Any idea how to go from here?
